spring:
  datasource:

    url: jdbc:mysql://localhost:3306/spring_user_001_giscord_db?useSSL=false&allowPublicKeyRetrieval=true
    username: spring_user_001
    password: springpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # (auto-creates tables)
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    enabled: false       # weâ€™ll rely on JPA auto-creation for now

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.socket.server: DEBUG
    org.springframework.web.socket.messaging: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.messaging.simp.stomp: TRACE


jwt:
  secret: "change-me-super-secret-and-long-enough" # override in env for prod
  expiration-ms: 3000000 # 50 mins



server:
  port: 8080
